DEFAULT_SERVICE_NAME = "Vocalis Pronunciation Assessment API"
DEFAULT_FRAME_RATE_HZ = 50.0

CONFIDENCE_MIN = 0.05
CONFIDENCE_MAX = 0.95
TRANSCRIPT_CONFIDENCE_MAX = 0.99

SUPPORTED_WEBSOCKET_AUDIO_ENCODING = "pcm_s16le"